### PR TITLE
Adding amLocal pipe, per code found here: https://github.com/reberinf…

### PR DESCRIPTION
**Pull request by benwilkins**
Note: This pull request is for the code that was written in [this fork ](https://github.com/reberinformatik/angular2-moment/commit/0d545cc9a5e14913bddcb00221faaa7c4529ef17#diff-bd4173df3baced7437261256a7041b36).

### CODE REVIEW

**Comment by urish** [comment]
Thanks! Seems like `local.spec.ts` should be called `local.pipe.spec.ts` (this is what causes the CI build to fail)

**Comment by benwilkins** [comment]
Hallelujah! All checks finally passed. 

[LGTM](https://www.lgtm.in/i/wCjdLiCln)

**Comment by urish** [comment]
Thanks! Love the gif :)

**Comment by urish** [comment]
Released as 1.6.0

**Pull request merged**
