### PR TITLE
Fix urish/angular2-moment#99 - Added supports for amCalendar custom formats

### PR DESCRIPTION
**Pull request by ykoehler**

### CODE REVIEW

**Comment by ykoehler** [comment]
{{ transaction.date | amCalendar:null:{sameDay:'[Today]', nextDay:'[Tomorrow]', nextWeek:'dddd', lastDay:'[Yesterday]', lastWeek:'[Last] dddd', sameElse:'l'} }}

This is what I used as a test, notice that with those new format the time is not displayed compared to the default behavior which is to output "Today at hh:mm"

**Comment by irsick** [comment]
Your pull request is at least third after mine and @arimus's.

https://github.com/urish/angular2-moment/pull/64

Welcome to the club :)

Btw, moment.js supports format as function.

**Comment by urish** [comment]
I hope to get 1.0 released by the end of the month, and then we'll have a PR-fest :)

Thanks for the contribution!

**Comment by urish** [comment]
Seems like it is already addressed by #64 ?

**Pull request closed without merging**
