### PR TITLE
feat(dateformat): add DateFormatPipe/amDateFormat

### PR DESCRIPTION
**Pull request by andreialecu**

### CODE REVIEW

**Comment by andreialecu** [comment]
Ping @urish :)

**Comment by urish** [comment]
Thanks!

**Comment by soumya92** [comment]
Any chance you could release a new version with this included? Thanks! :D

**Comment by urish** [comment]
Yes, will get to it tomorrow :)

**Comment by urish** [comment]
Released as `0.3.0`

**Pull request merged**
