### PR TITLE
Use peerDependencies instead of dependencies

### PR DESCRIPTION
**Pull request by hlehmann**
This would avoid conflict and redundancies with other libraries.

### CODE REVIEW

**Comment by urish** [comment]
Hi, thanks for your contribution! Can you point out why `peerDependencies` make more sense? 
Also, are there any other angular2 modules who took this approach? If there is a discussion or a blog post about this, I would love to read it and learn...

Thanks!

**Comment by hlehmann** [comment]
As anguar2 is a major library, peerDependencies let the developer have the final choice of the version (or not to install it) and also avoid that two different versions are installed. We expect to have a better control of client side libraries due to size constraints.

Some using peerDependencies
- angular2 itself prefer peerDependencies.
- https://github.com/valor-software/ng2-bootstrap/blob/master/package.json
- https://github.com/Urigo/angular2-meteor/blob/master/package.json

Ionic still use "dependencies".
Lot's doesn't precise angular at a dependency at all or use devDependencies.

I find an old article : https://nodejs.org/en/blog/npm/peer-dependencies/

It's finally hard to find unanimity, but peerDependencies or devDependencies seems to give more control.

**Comment by urish** [comment]
Thanks the references @hlehmann!

I am going to do a little more research on the subject and then see what the best option would be for `angular2`. 

What about `moment`?

**Comment by hlehmann** [comment]
Well if it's important to avoid multiple versions of a dependency, which is the case for client libraries, I would put moment in peerDependencies too.

**Comment by urish** [comment]
Ok, we will start with `angular2` for now, and see about `moment` later.

Thanks for the input!

**Pull request closed without merging**
