### PR TITLE
Adds `amFromUtc` pipe

### PR DESCRIPTION
**Pull request by connormlewis**
* Parse input as UTC formatted date using moment.utc()

This implements what `amUtc` did in the original angular-moment project. It was suggested in #159 and will help with issues mentioned in #122, #160, and possibly #150

### CODE REVIEW

**Comment by urish** [comment]
Thank you!

**Comment by arunas-smala** [comment]
@urish Could you please create new version tag :/? I need `amFromUtc` pipe but it's not available in `1.6.0` version

**Comment by urish** [comment]
Yes, I will soon

**Comment by urish** [comment]
Released as 1.7.0

**Comment by arunas-smala** [comment]
Thanks!

**Pull request merged**
