### PR TITLE
Added SubtractPipe and AddPipe

### PR DESCRIPTION
**Pull request by dustin486**
I added the functions for SubtractPipe and AddPipe. These are used as:
{{ mydate | amAdd : '2' : 'hours' }}
{{ mydate | amSubtract : '2' : 'hours' }}

### CODE REVIEW

**Comment by pisix** [comment]
@urish please can you merge this PR ?

**Comment by urish** [comment]
Eventually yes, but first of all I want to make sure that the existing project works with all setups (Ionic, rollup, protractor, AMD) and release 1.0.0. You can see #90, #91, #89 , #87, #85 , #82, #80  as examples for such issues

**Comment by urish** [comment]
@pisix Hi, can you please update the PR to align the file names with angular2 style guide convention?

i.e. use `add.pipe.ts` instead of `AddPipe.ts`, etc. 

I would love to see this feature as part of the upcoming 1.1.0 release :)

Thanks!

**Comment by urish** [comment]
@dustin486 Hi, can you please update the PR to align the file names with angular2 style guide convention?

i.e. use add.pipe.ts instead of AddPipe.ts, etc.

I would love to see this feature as part of the upcoming 1.1.0 release :)

Thanks!

**Comment by dustin486** [comment]
@urish Sure. I am at work until later tonight, but will do this tomorrow.

**Comment by urish** [comment]
Much appreciated!

**Comment by urish** [comment]
Ping

**Comment by dustin486** [comment]
@urish Sorry, I've been sick for a few days, still am. I don't know what happened to this one, but I messed it up merging my local copy with your version. I just created another fork, updated mine, and opened a new PR: https://github.com/urish/angular2-moment/pull/113

This one can be closed. Sorry about the confusion.

**Comment by urish** [comment]
I hope that you feel better now :-)

I will take a look at #113 soon!

**Pull request closed without merging**
