### PR TITLE
amLang pipe implemented

### PR DESCRIPTION
**Pull request by FallenRiteMonk**
As wanted in #154

### CODE REVIEW

**Comment by urish** [comment]
Thank you very much!

Actually, it would make more sense to align with moment.js naming convention, and call it `amLocale`. Do you also think so?

**Comment by FallenRiteMonk** [comment]
Yes! I just didn't do it because of the naming in PR #153!

It's your decision, if you want I can change it!

**Comment by urish** [comment]
Let's do it then :)

**Comment by FallenRiteMonk** [comment]
Ok give me a minute!

**Comment by urish** [comment]
Lovely, thanks!

**Comment by urish** [comment]
Released as 1.5.0

**Comment by sebrojas14** [comment]
Example?

**Comment by sebrojas14** [comment]
And what about a global config?

**Comment by sebrojas14** [comment]
`moment.locale('es')` works for change locale globally but if pipes use `import * as moment from 'moment/min/moment-with-locales';` instead of `import * as moment from 'moment';`. I tried to change tha in this library bu I always get an error (Could not find a declaration file for module 'moment/min/moment-with-locales'. 'c:/Users/Sebastián/Documents/GitHub/angular2-moment/node_modules/moment/min/moment-with-locales.js' implicitly has an 'any' type.   Try `npm install @types/moment/min/moment-with-locales` if it exists or add a new declaration (.d.ts) file containing `declare module 'moment/min/moment-with-locales';`) so I ended up making the pipe in my project (where I can import moment with locales)

**Pull request merged**
