### PR TITLE
(bug): add support for undefined date (#41)

### PR DESCRIPTION
**Pull request by amcdnl**

### CODE REVIEW

**Comment by urish** [comment]
Thanks!

**Comment by amcdnl** [comment]
@urish - any chance i could get you to do a release on npm? ;)

**Comment by urish** [comment]
I hope to do so today or tomorrow :)

**Comment by amcdnl** [comment]
Ok, this is blocking me from releasing my lib so i was hoping I didn't have to do `npm link` hackery until then.

**Comment by urish** [comment]
Released as 1.0.0-beta.6

**Comment by urish** [comment]
What lib are you working on?

**Comment by amcdnl** [comment]
Your awesome! Thank you!

Shot you a msg in Gitter to chat about the lib.

**Comment by urish** [comment]
Sure :) Which lib are you working on?

**Pull request merged**
