### PR TITLE
feat(*): add `amFromNow` pipe to mimic `moment().fromNow()` behavior

### LINKED ISSUE #45: moment.fromNow()
I would like to see http://momentjs.com/docs/#/displaying/fromnow/ implemented, is there a special reason why it is not supported, yet? Otherwise, I could work on a PR for that.

### PR DESCRIPTION
**Pull request by DethAriel**
Closes #45

### CODE REVIEW

**Comment by DethAriel** [comment]
@urish are there any changes required in order to have this one merged and released?

**Comment by urish** [comment]
Thank you for your contribution!

Seems like it does exactly what the `amTimeAgo` pipe does, can you please explain the rationale behind this?

**Comment by DethAriel** [comment]
hm... the `amTimeAgo` pipe didn't look like the thing I needed, so I haven't even digged into it. My bad, will close this PR now, since, as you mentioned, this case is already handled. Do you mind closing #45 then ?

**Comment by DethAriel** [comment]
The bad thing with `amTimeAgo` though consists in its name - `moment().from()` can also report on future dates, like `"in 6 months"`, and this pipe does not correctly represent such possibility

**Comment by urish** [comment]
true, though - from what I have seen, it is a common practice on the web (e.g. even in github I sometimes see "in a few seconds" for comments that were just posted, and probably there is some time drift between client and server)

**Pull request closed without merging**
